
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this template, fc Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author OPTIMUS
 */
public class Bittorent_Like extends javax.swing.JFrame {

    /**
     * Creates new form Bittorent_Like
     */
    public static peerinfo peer;
    public static int portlisten = 1991;
    public static int portdow = 1001;
    public static listen nghe;
    public static sendrequest gui;
    public static File f;

    public Bittorent_Like() {

        peer = new peerinfo();
        nghe = new listen();
        nghe.start();
        gui = new sendrequest();
        gui.peer = peer;
        gui.gui();

        initComponents();
        txtCatTapTin.setEditable(false);
        txtNoiFile.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtCatTapTin = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jCboChunk = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNoiFile = new javax.swing.JTextField();
        btnChonFileNoi = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        progStatus = new javax.swing.JProgressBar();
        lblStatus = new javax.swing.JLabel();
        btnBrowseDownloadChunk = new javax.swing.JButton();
        txtTaiTorrent = new javax.swing.JTextField();
        btnThongTin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Torrent downloader");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButton1.setText("Cắt tập tin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatTapTinActionPerformed(evt);
            }
        });

        jButton2.setText("Nối tập tin");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoiTapTinActionPerformed(evt);
            }
        });

        jButton3.setText("Tải tất cả");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiTatCaActionPerformed(evt);
            }
        });

        txtCatTapTin.setName(""); // NOI18N

        jButton4.setText("Chọn tập tin");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonCatTapTinActionPerformed(evt);
            }
        });

        jButton5.setText("Tải chunk đang chọn");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiChunkActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Torrent downloader");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Cắt tập tin:");

        jLabel3.setText("Danh sách chunk:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Nối tập tin:");

        txtNoiFile.setName(""); // NOI18N

        btnChonFileNoi.setText("Chọn tập tin");
        btnChonFileNoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonFileNoiActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Tải tập tin:");

        jPanel1.setBackground(new java.awt.Color(220, 220, 220));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatus)
                    .addComponent(progStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnBrowseDownloadChunk.setText("Chọn tập tin torrent");
        btnBrowseDownloadChunk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseDownloadChunkActionPerformed(evt);
            }
        });

        txtTaiTorrent.setEditable(false);
        txtTaiTorrent.setText("##");

        btnThongTin.setText("?");
        btnThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jCboChunk, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCatTapTin, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTaiTorrent, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnBrowseDownloadChunk))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(txtNoiFile, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnChonFileNoi))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThongTin)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCatTapTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoiFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChonFileNoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnBrowseDownloadChunk)
                    .addComponent(txtTaiTorrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCboChunk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * chọn file cần cắt
     */
    private void btnCatTapTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatTapTinActionPerformed

        CatFile c = new CatFile();
        String tenfile = txtCatTapTin.getText().trim();
        File f = new File(tenfile);
        lblStatus.setText("");

        if (f.exists()) {
            c.fi = new ThongTinTapTin(f);
            progStatus.setMinimum(0);
            progStatus.setMaximum(c.fi.getSochunk());
            c.addCustomListener(new CustomEventListener() {

                @Override
                public void onStart(CustomEventObject e) {
                    
                }

                @Override
                public void onOccur(CustomEventObject e) {
                    progStatus.setValue(e._value);
                    
                    Double phanTram = (e._value*1.0 / e._max)*100;
                    NumberFormat nf = new DecimalFormat("0");
                    
                    lblStatus.setText("Đang cắt tập tin " + nf.format(phanTram.doubleValue()) + "%...");
                }

                @Override
                public void onFinish(CustomEventObject e) {
                    lblStatus.setText("Cắt tập tin hoàn tất (" + e._max + " chunks)...");
                }
            });
            
            c.start();
        }
        else
        {
            JOptionPane.showMessageDialog(new JPanel(), "Tập tin không tồn tại!");
            lblStatus.setText("Tập tin không tồn tại!");
        }
    }//GEN-LAST:event_btnCatTapTinActionPerformed
    /*
     * ghép file
     */
    private void btnNoiTapTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoiTapTinActionPerformed
        // TODO add your handling code here:
        NoiFile c = new NoiFile();
        String filename = txtNoiFile.getText().trim();
        File f = new File(filename);
        lblStatus.setText("");
        
        FileInputStream in = null;
        int sochunk = 0;
        try {
            in = new FileInputStream(f);
            Scanner input = new Scanner(in);
            sochunk = input.nextInt(); // đọc số lượng chunks
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(new JPanel(), "Lỗi\n\n" + ex.getMessage());
            return;
        } finally {
            try {
                in.close();
            } catch (IOException ex) {
                Logger.getLogger(Bittorent_Like.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        if (f.exists()) {
            c.fInfo = new ThongTinTapTin(f);
            c.fInfo.setSochunk(sochunk);
            
            progStatus.setMinimum(0);
            progStatus.setMaximum(c.fInfo.getSochunk());
            c.addCustomListener(new CustomEventListener() {

                @Override
                public void onStart(CustomEventObject e) {
                    
                }

                @Override
                public void onOccur(CustomEventObject e) {
                    progStatus.setValue(e._value);
                    
                    Double phanTram = (e._value*1.0 / e._max)*100;
                    NumberFormat nf = new DecimalFormat("0");
                    
                    lblStatus.setText("Đang nối tập tin " + nf.format(phanTram.doubleValue()) + "%...");
                }

                @Override
                public void onFinish(CustomEventObject e) {
                    lblStatus.setText("Nối tập tin hoàn tất (" + e._object1.toString() + ") 100%...");
                }
            });
            
            c.start();
        }
        else
        {
            JOptionPane.showMessageDialog(new JPanel(), "Tập tin không tồn tại!");
            lblStatus.setText("Tập tin không tồn tại!");
        }
        
    }//GEN-LAST:event_btnNoiTapTinActionPerformed
    /*
     * chọn file cần dow
     */
    private void btnTaiTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiTatCaActionPerformed
        // TODO add your handling code here:
        
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new FileNameExtensionFilter("Torrent file (*.torrent)", "torrent"));
        fc.setMultiSelectionEnabled(false);
       
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
        
            if (fc.getSelectedFiles() != null) {
                FileInputStream in = null;
                int sochunk = 0;
                try {
                    in = new FileInputStream(fc.getSelectedFile());
                    Scanner input = new Scanner(in);
                    sochunk = input.nextInt();
                } catch (Exception ex) {
                    ex.printStackTrace();
                    //JOptionPane.showMessageDialog(new JPanel(), "Lỗi\n\n" + ex.getMessage());
                    return;
                }
                String ten = fc.getSelectedFile().getName();
                ten = ten.substring(0, ten.length() - 8);
                ThongTinTapTin fi = new ThongTinTapTin();
                fi.setTenfile(ten);
                fi.setSochunk(sochunk);

                txtCatTapTin.setText(fc.getSelectedFile().getAbsolutePath());
                DownloadChunk dow;
                for (int i = 0; i < sochunk; i++) {
                    File f = new File(ThongTinChunk.ddmacdinh + ten + "/" + ten + "_" + (i + 1 + ".chunk"));
                    if (!f.exists()) {
                        // lúc này yêu cầu gửi
                        dow = new DownloadChunk();
                        dow.file = fi;
                        dow.peer = peer;
                        dow.chunkdow = i + 1;
                        System.out.println("dang down chunk: " + (i + 1));
                        dow.start();
                        System.out.println("da down xong chunk: " + (i + 1));
                    } else {
                    }
                }
            }
        }
    }//GEN-LAST:event_btnTaiTatCaActionPerformed

    /*
     * down tuần tự từng file
     */
    private void btnChonCatTapTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonCatTapTinActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.setMultiSelectionEnabled(false);
        
        if(fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            txtCatTapTin.setText(fc.getSelectedFile().getAbsolutePath());
            LogFile.Write("@Cắt tập tin: Mở tập tin " + fc.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_btnChonCatTapTinActionPerformed

    /*
     * dow chunk chọn trên combox
     */
    private void btnTaiChunkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiChunkActionPerformed
        // TODO add your handling code here:

        String chunk = jCboChunk.getSelectedItem().toString();
        DownloadChunk dow = new DownloadChunk();
        ThongTinTapTin fo = new ThongTinTapTin();
        String tenfile = f.getName().substring(0, f.getName().length() - 8); // cắt bỏ đuôi .tottrent
        fo.setTenfile(tenfile);
        dow.file = fo;
        dow.peer = peer;
        String[] mang = chunk.split("_");
        String tam = mang[1];
        tam = tam.substring(0, tam.length() - 6);
        dow.chunkdow = Integer.parseInt(tam);
        System.out.println("Đang dow chunk: " + mang[1]);
        dow.start();
        //System.out.println("Đã dow xong chunk: " + mang[1]);


    }//GEN-LAST:event_btnTaiChunkActionPerformed

    private void btnChonFileNoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonFileNoiActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.setMultiSelectionEnabled(false);// không cho chọn nhiều file
        fc.setFileFilter(new FileNameExtensionFilter("Torrent file (*.torrent)", "torrent"));
        
        if(fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            txtNoiFile.setText(fc.getSelectedFile().getAbsolutePath());
            LogFile.Write("@Nối tập tin: Mở tập tin " + fc.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_btnChonFileNoiActionPerformed

    private void btnThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTinActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(new JFrame(), "Thông tin nhóm thực hiện:\n\nBùi Bá Lộc - 1241363\nDương Diệu Pháp - 1241378");
    }//GEN-LAST:event_btnThongTinActionPerformed

    /**
     * Dow
     * @param evt 
     */
    private void btnBrowseDownloadChunkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseDownloadChunkActionPerformed
        // TODO add your handling code here:
        
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new FileNameExtensionFilter("Torrent file (*.torrent)", "torrent"));
        fc.setMultiSelectionEnabled(false);
       
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            if (fc.getSelectedFile() != null) {
                txtTaiTorrent.setText(fc.getSelectedFile().getAbsolutePath());
                LogFile.Write("@Tải torrent: Mở tập tin " + fc.getSelectedFile().getAbsolutePath());
                
                FileInputStream fis = null;
                f = fc.getSelectedFile(); // chọn file cần dow
                int sochunk = 0;
                try {
                    fis = new FileInputStream(fc.getSelectedFile());
                    Scanner scan = new Scanner(fis);
                    sochunk = scan.nextInt();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }

                String ten = fc.getSelectedFile().getName();
                ten = ten.substring(0, ten.length() - 8);
                ThongTinTapTin fi = new ThongTinTapTin();
                fi.setTenfile(ten);
                fi.setSochunk(sochunk);

                txtCatTapTin.setText(fc.getSelectedFile().getAbsolutePath());
                for (int i = 0; i < sochunk; i++) {
                    File f = new File(ThongTinChunk.ddmacdinh + ten + "/" + ten + "_" + (i + 1 + ".chunk"));

                    if (!f.exists()) {
                        jCboChunk.enable(true);
                        String chunkCanDow = f.getName();
                        jCboChunk.addItem(chunkCanDow);
                    }
                }
            }
        }
        
    }//GEN-LAST:event_btnBrowseDownloadChunkActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        LogFile.Write("#START_PROGRAM-----------------------------------------------------");
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        LogFile.Write("#END_PROGRAM-------------------------------------------------------");
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bittorent_Like.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bittorent_Like.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bittorent_Like.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bittorent_Like.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bittorent_Like().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowseDownloadChunk;
    private javax.swing.JButton btnChonFileNoi;
    private javax.swing.JButton btnThongTin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jCboChunk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JProgressBar progStatus;
    private javax.swing.JTextField txtCatTapTin;
    private javax.swing.JTextField txtNoiFile;
    private javax.swing.JTextField txtTaiTorrent;
    // End of variables declaration//GEN-END:variables
}
